---
title: "Covid-19"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: rows
runtime: shiny
---


```{r}
library(tidyverse)
library(dplyr)
library(lubridate)
library(plotly)
library(shinydashboard)
library(flexdashboard)
library(zoo)

df <- read_csv('https://coronavirus.data.gov.uk/downloads/csv/coronavirus-cases_latest.csv')

deaths <- read_csv('https://coronavirus.data.gov.uk/downloads/csv/coronavirus-deaths_latest.csv')


df <- df %>%  
  rename(cases=`Daily lab-confirmed cases`, day =`Specimen date`, area_name='Area name', area_type = `Area type`)

deaths <- deaths %>%  
  rename(deaths=`Daily change in deaths`, day =`Reporting date`, area_name='Area name', area_type = `Area type`)


# add columns to identify data for past 7 and 14 days

one_week_ago = Sys.Date() - 7
two_weeks_ago = one_week_ago - 7

df <- df %>%
mutate(date_range = case_when(day >= one_week_ago ~ 'past7days',
                              day >= two_weeks_ago & day < one_week_ago ~ "past7-14days"))


deaths <- deaths %>%
mutate(date_range = case_when(day >= one_week_ago+1 ~ 'past7days',
                              day >= two_weeks_ago+1 & day < one_week_ago+1 ~ "past7-14days"))

# calculate last week cases per area/region

cases_lw_per_area = df %>% filter(date_range == 'past7days', area_type == "Lower tier local authority") %>% group_by(area_name) %>% summarise(total = sum(cases))
cases_lw_per_regions = df %>% filter(date_range == 'past7days', area_type == "Region") %>% group_by(area_name) %>% summarise(total = sum(cases))


# calculate last week and 2 weeks ago cases per area for lockdown forecast
compare_weeks = df %>% 
  filter(is.na(date_range) == FALSE, area_type == "Lower tier local authority") %>% 
  group_by(area_name, date_range) %>% 
  summarise(total = sum(cases)) %>% 
  spread(date_range, total) %>%
  mutate(diff = past7days - `past7-14days`) %>%
  arrange(-diff)


```


England
=======================================================================


Row {data-height=100}
-------------------------------------

### Total England cases


```{r}
england <- df %>% filter(area_type=='Nation')
total_cases = england[which.max(england$day),]

valueBox(as.character(total_cases$`Cumulative lab-confirmed cases`), caption = "total cases", color = "#05668d")

```

### Last data England cases


```{r}
england <- df %>% filter(area_type=='Nation') %>%
  group_by(date_range) %>% 
  summarise(total = sum(cases))

last7_days = england %>% filter(date_range == "past7days")
last7_14_days = england %>% filter(date_range == "past7-14days")

pct = round((last7_days$total- last7_14_days$total) / last7_14_days$total*100,0)

if (pct > 0) {pct = paste("+", pct, sep = "")}

valueBox( paste("+ ",as.character(last7_days$total)," (", pct,"%)"), caption = "cases last week", color = "#05668d")

```

### Total England deaths


```{r}
england <- deaths %>% filter(area_type=='Nation', area_name == 'England')
total_deaths = england[which.max(england$day),]

valueBox(as.character(total_deaths$`Cumulative deaths`) , caption = "total deaths" , color = '#02c39a')

```


### Last data England deaths


```{r}
england <- deaths %>% filter(area_type=='Nation', area_name == 'England') %>%
  group_by(date_range) %>% 
  summarise(total = sum(deaths))

last7_days = england %>% filter(date_range == "past7days")
last7_14_days = england %>% filter(date_range == "past7-14days")

pct = round((last7_days$total- last7_14_days$total) / last7_14_days$total*100,0)

if (pct > 0) {pct = paste("+", pct, sep = "")}

valueBox( paste("+", as.character(last7_days$total),"(", pct,"%)"), caption = "deaths last week", color = '#02c39a')

```


Row {data-height=450}
-------------------------------------

### **England cases by local authority** 


```{r}

local = df %>%  
  filter(area_type == "Lower tier local authority")


library(shiny)

ui <- fluidPage(
  titlePanel("Choose your borough:"),
  
  # Sidebar with a slider input for number of bins 
  sidebarLayout(position = "left", fluid = TRUE,
    sidebarPanel(width =3,
                 
      valueBoxOutput("box"),
      selectInput(inputId = "area_name", label = (""),
                  choices = unique(local$area_name), selected = 'Reading'
      )),
    
    
    mainPanel(width =6,
      plotlyOutput(outputId = "plot", height = "200px")
    )
  )
)


# Define server logic required to draw a histogram
server <- function(input, output) {
  filtered_data<- reactive({
    dplyr::filter(local, local$area_name==input$area_name)
  })
  
  filtered_data_lw_total<- reactive({
    dplyr::filter(cases_lw_per_area, cases_lw_per_area$area_name==input$area_name)
  })

  output$plot <- renderPlotly({

    
   g = local %>% 
      filter(area_name %in% input$area_name) %>% 
      ggplot() +
      geom_bar(stat = "identity", fill = '#028090', aes(x= filtered_data()$day, y= filtered_data()$cases, 
              text = paste(" date:",filtered_data()$day, "\n", "cases:", filtered_data()$cases ))) + 
      geom_line(aes(x= filtered_data()$day, y=rollmean(filtered_data()$cases, 7, na.pad=TRUE))) +
      xlab("") + ylab("cases") + 
      theme_classic() 


  ggplotly(g, tooltip = "text")
    
  })
  
  output$box <- renderValueBox({
  valueBox(paste(filtered_data_lw_total()$total, "cases were recorded last week in"))
   })

}


shinyApp(ui = ui, server = server)


```





Row {data-height=450}
-------------------------------------

### **England cases by region**


```{r}

regions = df %>% filter(area_type=='Region')


library(shiny)

ui <- fluidPage(
  titlePanel("Choose your region:"),
  
  # Sidebar with a slider input for number of bins 
  sidebarLayout(position = "left", fluid = TRUE,
    sidebarPanel(width =3,
      valueBoxOutput("box"),
      
      selectInput(inputId = "area_name", label = (""),
                  choices = unique(regions$area_name), selected = 'South East'
      )
      
      
      ),
    

    mainPanel(width = 6,
              plotlyOutput(outputId = "plot", height = "200px"))))



# Define server logic required to draw a histogram
server <- function(input, output) {
  filtered_data<- reactive({
    dplyr::filter(regions, regions$area_name==input$area_name)
  })

    filtered_data_lw_total<- reactive({
    dplyr::filter(cases_lw_per_regions, cases_lw_per_regions$area_name==input$area_name)
  })

    
  output$plot <- renderPlotly({
    
   g <- regions %>% 
      filter(area_name %in% input$area_name) %>%
      ggplot() +
      geom_bar(stat = "identity", fill = '#00a896', aes(x= filtered_data()$day, y= filtered_data()$cases, 
                 text = paste(" date:",filtered_data()$day, "\n", "cases:", filtered_data()$cases))) + 
      geom_line(aes(x = filtered_data()$day, y=rollmean(filtered_data()$cases, 7, na.pad=TRUE))) +
      xlab("") + ylab("cases") + 
      theme_classic() 

  ggplotly(g, tooltip = "text")

  })
  
  output$box <- renderValueBox({
    valueBox(paste(filtered_data_lw_total()$total, "cases were recorded last week in"))
   })
}


shinyApp(ui = ui, server = server)
```









Row
-------------------------------------

### **England cases**

```{r}
england = df %>% filter(area_type=='Nation') %>%
  group_by(day) %>% 
  summarise(total = sum(cases))

g <- england %>%  ggplot()+
                            geom_col(fill = '#02c39a', aes(x=day, y=total, text = paste(" date:", day, "\n", "cases:", total))) +
                            theme_classic() +
                            xlab("") + ylab("cases") +
                            geom_line(aes(x=day, y=rollmean(total, 7, na.pad=TRUE)))


  ggplotly(g, tooltip = "text")

```


### **UK deaths by nation**

```{r}
deaths_by_nation = deaths %>% filter(area_type=='Nation') %>%
  group_by(day, area_name) %>% 
  summarise(total = sum(deaths))

g <- deaths_by_nation %>%  ggplot(aes(x=day, y=total, fill = area_name)) +
                           geom_col() + 
                           theme_classic() +
                           xlab("") + ylab("deaths") + scale_fill_manual(name = "",values = c("#02c39a", "#05668d", "#028090", "#00a896"))# +
    #theme(legend.position = 'bottom')


ggplotly(g)   %>%
  layout(legend = list(orientation = "h", x = 0.2, y = -0.1)
    )

```





Row
-------------------------------------


### **Areas at high lockdown risk**

```{r}
library(DT)
datatable(compare_weeks)
```
